; Developed by Amine Saoud ibn al-Bashir.
; NanoKit Drone 4X camera and audio node.
[env:nanokit_camera_audio]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
  -D NANOKIT_DRONE_4X_CAMERA_NODE=1
