; Developed by Amine Saoud ibn al-Bashir.
; NanoKit Drone 4X (Quadcopter) reference firmware.
[env:nanokit_esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
  -D NANOKIT_DRONE_4X_BLE=1
