; Developed by Amine Saoud ibn al-Bashir.
; NanoKit Drone 4X (Quadcopter) Wi-Fi flight-controller firmware.
[platformio]
data_dir = ../web_controller

[env:nanokit_esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs

build_flags =
  -D NANOKIT_DRONE_4X_WIFI=1

lib_deps =
  links2004/WebSockets
