#!/usr/bin/env python3
# Developed by Amine Saoud ibn al-Bashir.
"""Generate repository tree and project catalogs for NanoKit-ESP32."""

from __future__ import annotations

import os
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ROOT_README_TREE_START = "<!-- GENERATED_REPOSITORY_TREE:START -->"
ROOT_README_TREE_END = "<!-- GENERATED_REPOSITORY_TREE:END -->"

SKIP_DIRS = {
    ".git",
    ".pio",
    ".pioenvs",
    ".piolibdeps",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    "__pycache__",
    "build",
    "dist",
    "htmlcov",
    "node_modules",
    "venv",
    ".venv",
    "env",
}

SKIP_FILES = {
    ".DS_Store",
    "Thumbs.db",
}

TOP_LEVEL_AREAS = [
    ("examples_on_platformio", "Focused PlatformIO examples"),
    ("applications_on_platformio", "Complete multi-part applications"),
    ("open_source_projects", "Original open-source-inspired NanoKit projects"),
    ("graduation_projects", "Academic and thesis projects"),
    ("tutorials", "Learning paths and tutorials"),
    ("articles", "Technical articles"),
    ("docs", "Core documentation"),
    ("simulator", "Simulation resources"),
    ("templates", "Reusable templates"),
    ("assets", "Shared assets"),
]


def read_title(readme: Path, fallback: str) -> str:
    if not readme.exists():
        return fallback.replace("_", " ").replace("-", " ").title()
    for line in readme.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback.replace("_", " ").replace("-", " ").title()


def has_file(path: Path, relative: str) -> str:
    return "yes" if (path / relative).exists() else "no"


def list_project_dirs(area: str) -> list[Path]:
    root = ROOT / area
    if not root.exists():
        return []
    return sorted(
        [item for item in root.iterdir() if item.is_dir() and item.name not in SKIP_DIRS],
        key=lambda item: item.name.lower(),
    )


def build_tree(root: Path) -> str:
    lines = [root.name + "/"]

    def walk(directory: Path, prefix: str = "") -> None:
        entries = [
            item
            for item in sorted(directory.iterdir(), key=lambda path: (path.is_file(), path.name.lower()))
            if item.name not in SKIP_FILES and not (item.is_dir() and item.name in SKIP_DIRS)
        ]
        for index, item in enumerate(entries):
            connector = "`-- " if index == len(entries) - 1 else "|-- "
            lines.append(f"{prefix}{connector}{item.name}{'/' if item.is_dir() else ''}")
            if item.is_dir():
                extension = "    " if index == len(entries) - 1 else "|   "
                walk(item, prefix + extension)

    walk(root)
    return "\n".join(lines)


def write_repository_tree() -> None:
    body = f"""# NanoKit-ESP32 Repository Tree

This file is generated by `tools/update_repository_index.py`.

**Developed by Amine Saoud ibn al-Bashir.**

Run the generator after adding, moving, or deleting examples, applications, documentation, or open-source projects.

```text
{build_tree(ROOT)}
```
"""
    (ROOT / "REPOSITORY_TREE.md").write_text(body, encoding="utf-8", newline="\n")


def write_root_readme_tree() -> None:
    """Replace only the generated tree block embedded in the root README."""
    readme = ROOT / "README.md"
    content = readme.read_text(encoding="utf-8")
    start_index = content.find(ROOT_README_TREE_START)
    end_index = content.find(ROOT_README_TREE_END)
    if start_index < 0 or end_index < 0 or end_index <= start_index:
        raise RuntimeError("README.md is missing its generated repository tree markers.")

    generated_block = (
        f"{ROOT_README_TREE_START}\n"
        f"```text\n{build_tree(ROOT)}\n```\n"
        f"{ROOT_README_TREE_END}"
    )
    updated = (
        content[:start_index]
        + generated_block
        + content[end_index + len(ROOT_README_TREE_END):]
    )
    readme.write_text(updated, encoding="utf-8", newline="\n")


def write_examples_catalog() -> None:
    rows = []
    for project in list_project_dirs("examples_on_platformio"):
        title = read_title(project / "README.md", project.name)
        rows.append(
            "| "
            + " | ".join(
                [
                    f"[{title}]({project.name}/README.md)",
                    "yes" if (project / "platformio.ini").exists() else "no",
                    has_file(project, "src/main.cpp"),
                    has_file(project, "docs/Wiring.md"),
                    has_file(project, "docs/Implementation_Guide.md"),
                    "yes" if (project / "images").exists() else "no",
                ]
            )
            + " |"
        )

    table = "\n".join(rows) if rows else "| No examples yet | no | no | no | no | no |"
    body = f"""# Examples on PlatformIO

Focused NanoKit Integrated ESP32 examples. Each example should remain small, buildable, documented, and aligned with `docs/software/platformio-example-standard.md`.

This catalog is generated by `tools/update_repository_index.py`.

**Developed by Amine Saoud ibn al-Bashir.**

| Example | PlatformIO | Source | Wiring | Implementation | Images |
|---|---|---|---|---|---|
{table}

## Maintenance

After adding a new example, run:

```bash
python tools/update_repository_index.py
```
"""
    (ROOT / "examples_on_platformio" / "README.md").write_text(body, encoding="utf-8", newline="\n")


def write_area_catalog(area: str, title: str, description: str) -> None:
    rows = []
    for project in list_project_dirs(area):
        project_title = read_title(project / "README.md", project.name)
        rows.append(
            "| "
            + " | ".join(
                [
                    f"[{project_title}]({project.name}/README.md)",
                    has_file(project, "README.md"),
                    has_file(project, "firmware/platformio.ini"),
                    "yes" if (project / "docs").exists() else "no",
                    "yes" if (project / "images").exists() else "no",
                ]
            )
            + " |"
        )

    table = "\n".join(rows) if rows else "| No projects yet | no | no | no | no |"
    body = f"""# {title}

{description}

This catalog is generated by `tools/update_repository_index.py`.

**Developed by Amine Saoud ibn al-Bashir.**

| Project | README | Firmware | Docs | Images |
|---|---|---|---|---|
{table}
"""
    (ROOT / area / "README.md").write_text(body, encoding="utf-8", newline="\n")


def write_root_index() -> None:
    rows = []
    for area, purpose in TOP_LEVEL_AREAS:
        path = ROOT / area
        rows.append(f"| [{area}]({area}/README.md) | {purpose} | {len(list_project_dirs(area))} |")
    table = "\n".join(rows)
    body = f"""# NanoKit-ESP32 Index

This file is generated by `tools/update_repository_index.py`.

**Developed by Amine Saoud ibn al-Bashir.**

| Area | Purpose | Direct Folders |
|---|---|---:|
{table}

See `REPOSITORY_TREE.md` for the full generated tree.
"""
    (ROOT / "REPOSITORY_INDEX.md").write_text(body, encoding="utf-8", newline="\n")


def main() -> None:
    os.chdir(ROOT)
    write_repository_tree()
    write_root_readme_tree()
    write_root_index()
    write_examples_catalog()
    write_area_catalog(
        "open_source_projects",
        "Open Source Projects",
        "Original NanoKit-oriented projects inspired by open-source engineering practices. Do not copy external project code.",
    )
    write_area_catalog(
        "applications_on_platformio",
        "Applications on PlatformIO",
        "Complete NanoKit Integrated ESP32 applications with firmware, documentation, media, and reusable assets.",
    )
    print("Updated REPOSITORY_TREE.md, REPOSITORY_INDEX.md, and generated catalogs.")


if __name__ == "__main__":
    main()
